insert into tasks (name, xp, period, sort_order) values
  ('No screens before tasks or 8 AM', 100, 'morning', 1),
  ('Unload dishwasher', 50, 'morning', 2),
  ('Walk dogs', 100, 'morning', 3),
  ('Take shower', 50, 'morning', 4),
  ('Skin + health routine', 50, 'morning', 5),
  ('Draw or create', 50, 'morning', 6),
  ('Stretch + move routine', 100, 'morning', 7),
  ('Brush teeth', 50, 'morning', 8),
  ('Done & ready by 9 AM', 50, 'morning', 9),
  ('Read 15 minutes', 100, 'afternoon', 1),
  ('Meal with no screen time', 100, 'afternoon', 2),
  ('Done eating by 8 PM', 50, 'bedtime', 1),
  ('Skip sugar & dessert', 50, 'bedtime', 2),
  ('Shower or bath', 50, 'bedtime', 3),
  ('Brush teeth (bedtime)', 50, 'bedtime', 4),
  ('Track protein for the day (50g+ minimum)', 100, 'health', 1),
  ('Apple Watch activity (50+ active calories)', 100, 'health', 2),
  ('Piano', 100, 'weekly', 1),
  ('Video edit project', 100, 'weekly', 2),
  ('Math', 100, 'weekly', 3),
  ('Handwriting', 100, 'weekly', 4),
  ('Journal', 100, 'weekly', 5),
  ('Skill building (Duolingo)', 100, 'weekly', 6),
  ('Put laundry away', 100, 'bonus', 1),
  ('Vacuum/sweep', 100, 'bonus', 2),
  ('Take out garbage', 50, 'bonus', 3);
